import streamlit as st
from tensorflow.keras.models import load_model
from PIL import Image
import numpy as np
from sklearn.metrics import f1_score

# Define the custom metric function F1_score
def F1_score(y_true, y_pred):
    # Calculate F1 score
    f1 = f1_score(y_true, y_pred, average='macro')  # Change 'macro' to 'micro' or 'weighted' if needed
    return f1

# Load the model
model = load_model('model.h5', custom_objects={'F1_score': F1_score})  # Replace 'model.h5' with the correct path

# Bird classes
bird_classes = [
    "ABBOTTS BABBLER","ABBOTTS BABBLER", "ABBOTTS BOOBY", "ABYSSINIAN GROUND HORNBILL", "AFRICAN CROWNED CRANE",
    "AFRICAN EMERALD CUCKOO", "AFRICAN FIREFINCH", "AFRICAN OYSTER CATCHER", "AFRICAN PIED HORNBILL",
    "AFRICAN PYGMY GOOSE", "ALBATROSS", "ALBERTS TOWHEE", "ALEXANDRINE PARAKEET", "ALPINE CHOUGH",
    "ALTAMIRA YELLOWTHROAT", "AMERICAN AVOCET", "AMERICAN BITTERN", "AMERICAN COOT", "AMERICAN FLAMINGO",
    "AMERICAN GOLDFINCH", "AMERICAN KESTREL", "AMERICAN PIPIT", "AMERICAN REDSTART", "AMERICAN ROBIN",
    "AMERICAN WIGEON", "AMETHYST WOODSTAR", "ANDEAN GOOSE", "ANDEAN LAPWING", "ANDEAN SISKIN", "ANHINGA",
    "ANIANIAU", "ANNAS HUMMINGBIRD", "ANTBIRD", "ANTILLEAN EUPHONIA", "APAPANE", "APOSTLEBIRD",
    "ARARIPE MANAKIN", "ASHY STORM PETREL", "ASHY THRUSHBIRD", "ASIAN CRESTED IBIS", "ASIAN DOLLARD BIRD",
    "ASIAN GREEN BEE EATER", "ASIAN OPENBILL STORK", "AUCKLAND SHAQ", "AUSTRAL CANASTERO",
    "AUSTRALASIAN FIGBIRD", "AVADAVAT", "AZARAS SPINETAIL", "AZURE BREASTED PITTA", "AZURE JAY",
    "AZURE TANAGER", "AZURE TIT", "BAIKAL TEAL", "BALD EAGLE", "BALD IBIS", "BALI STARLING",
    "BALTIMORE ORIOLE", "BANANAQUIT", "BAND TAILED GUAN", "BANDED BROADBILL", "BANDED PITA", "BANDED STILT",
    "BAR-TAILED GODWIT", "BARN OWL", "BARN SWALLOW", "BARRED PUFFBIRD", "BARROWS GOLDENEYE",
    "BAY-BREASTED WARBLER", "BEARDED BARBET", "BEARDED BELLBIRD", "BEARDED REEDLING", "BELTED KINGFISHER",
    "BIRD OF PARADISE", "BLACK AND YELLOW BROADBILL", "BLACK BAZA", "BLACK COCKATO", "BLACK FACED SPOONBILL",
    "BLACK FRANCOLIN", "BLACK HEADED CAIQUE", "BLACK NECKED STILT", "BLACK SKIMMER", "BLACK SWAN",
    "BLACK TAIL CRAKE", "BLACK THROATED BUSHTIT", "BLACK THROATED HUET", "BLACK THROATED WARBLER",
    "BLACK VENTED SHEARWATER", "BLACK VULTURE", "BLACK-CAPPED CHICKADEE", "BLACK-NECKED GREBE",
    "BLACK-THROATED SPARROW", "BLACKBURNIAM WARBLER", "BLONDE CRESTED WOODPECKER", "BLOOD PHEASANT",
    "BLUE COAU", "BLUE DACNIS", "BLUE GRAY GNATCATCHER", "BLUE GROSBEAK", "BLUE GROUSE", "BLUE HERON",
    "BLUE MALKOHA", "BLUE THROATED TOUCANET", "BOBOLINK", "BORNEAN BRISTLEHEAD", "BORNEAN LEAFBIRD",
    "BORNEAN PHEASANT", "BRANDT CORMARANT", "BREWERS BLACKBIRD", "BROWN CREPPER", "BROWN HEADED COWBIRD",
    "BROWN NOODY", "BROWN THRASHER", "BUFFLEHEAD", "BULWERS PHEASANT", "BURCHELLS COURSER", "BUSH TURKEY",
    "CAATINGA CACHOLOTE", "CABOTS TRAGOPAN", "CACTUS WREN", "CALIFORNIA CONDOR", "CALIFORNIA GULL",
    "CALIFORNIA QUAIL", "CAMPO FLICKER", "CANARY", "CANVASBACK", "CAPE GLOSSY STARLING", "CAPE LONGCLAW",
    "CAPE MAY WARBLER", "CAPE ROCK THRUSH", "CAPPED HERON", "CAPUCHINBIRD", "CARMINE BEE-EATER",
    "CASPIAN TERN", "CASSOWARY", "CEDAR WAXWING", "CERULEAN WARBLER", "CHARA DE COLLAR", "CHATTERING LORY",
    "CHESTNET BELLIED EUPHONIA", "CHESTNUT WINGED CUCKOO", "CHINESE BAMBOO PARTRIDGE", "CHINESE POND HERON",
    "CHIPPING SPARROW", "CHUCAO TAPACULO", "CHUKAR PARTRIDGE", "CINNAMON ATTILA", "CINNAMON FLYCATCHER",
    "CINNAMON TEAL", "CLARKS GREBE", "CLARKS NUTCRACKER", "COCK OF THE  ROCK", "COCKATOO", "COLLARED ARACARI",
    "COLLARED CRESCENTCHEST", "COMMON FIRECREST", "COMMON GRACKLE", "COMMON HOUSE MARTIN", "COMMON IORA",
    "COMMON LOON", "COMMON POORWILL", "COMMON STARLING", "COPPERSMITH BARBET", "COPPERY TAILED COUCAL",
    "CRAB PLOVER", "CRANE HAWK", "CREAM COLORED WOODPECKER", "CRESTED AUKLET", "CRESTED CARACARA",
    "CRESTED COUA", "CRESTED FIREBACK", "CRESTED KINGFISHER", "CRESTED NUTHATCH", "CRESTED OROPENDOLA",
    "CRESTED SERPENT EAGLE", "CRESTED SHRIKETIT", "CRESTED WOOD PARTRIDGE", "CRIMSON CHAT", "CRIMSON SUNBIRD",
    "CROW", "CUBAN TODY", "CUBAN TROGON", "CURL CRESTED ARACURI", "D-ARNAUDS BARBET", "DALMATIAN PELICAN",
    "DARJEELING WOODPECKER", "DARK EYED JUNCO", "DAURIAN REDSTART", "DEMOISELLE CRANE", "DOUBLE BARRED FINCH",
    "DOUBLE BRESTED CORMARANT", "DOUBLE EYED FIG PARROT", "DOWNY WOODPECKER", "DUSKY LORY", "DUSKY ROBIN",
    "EARED PITA", "EASTERN BLUEBIRD", "EASTERN BLUEBONNET", "EASTERN GOLDEN WEAVER", "EASTERN MEADOWLARK",
    "EASTERN ROSELLA", "EASTERN TOWEE", "EASTERN WIP POOR WILL", "EASTERN YELLOW ROBIN", "ECUADORIAN HILLSTAR",
    "EGYPTIAN GOOSE", "ELEGANT TROGON", "ELLIOTS  PHEASANT", "EMERALD TANAGER", "EMPEROR PENGUIN", "EMU",
    "ENGGANO MYNA", "EURASIAN BULLFINCH", "EURASIAN GOLDEN ORIOLE", "EURASIAN MAGPIE", "EUROPEAN GOLDFINCH",
    "EUROPEAN TURTLE DOVE", "EVENING GROSBEAK", "FAIRY BLUEBIRD", "FAIRY PENGUIN", "FAIRY TERN", "FAN TAILED WIDOW",
    "FASCIATED WREN", "FIERY MINIVET", "FIORDLAND PENGUIN", "FIRE TAILLED MYZORNIS", "FLAME BOWERBIRD",
    "FLAME TANAGER", "FOREST WAGTAIL", "FRIGATE", "FRILL BACK PIGEON", "GAMBELS QUAIL", "GANG GANG COCKATOO",
    "GILA WOODPECKER", "GILDED FLICKER", "GLOSSY IBIS", "GO AWAY BIRD", "GOLD WING WARBLER", "GOLDEN BOWER BIRD",
    "GOLDEN CHEEKED WARBLER", "GOLDEN CHLOROPHONIA", "GOLDEN EAGLE", "GOLDEN PARAKEET", "GOLDEN PHEASANT",
    "GOLDEN PIPIT", "GOULDIAN FINCH", "GRANDALA", "GRAY CATBIRD", "GRAY KINGBIRD", "GRAY PARTRIDGE",
    "GREAT ARGUS", "GREAT GRAY OWL", "GREAT JACAMAR", "GREAT KISKADEE", "GREAT POTOO", "GREAT TINAMOU",
    "GREAT XENOPS", "GREATER PEWEE", "GREATER PRAIRIE CHICKEN", "GREATOR SAGE GROUSE", "GREEN BROADBILL",
    "GREEN JAY", "GREEN MAGPIE", "GREEN WINGED DOVE", "GREY CUCKOOSHRIKE", "GREY HEADED FISH EAGLE",
    "GREY PLOVER", "GROVED BILLED ANI", "GUINEA TURACO", "GUINEAFOWL", "GURNEYS PITTA", "GYRFALCON", "HAMERKOP",
    "HARLEQUIN DUCK", "HARLEQUIN QUAIL", "HARPY EAGLE", "HAWAIIAN GOOSE", "HAWFINCH", "HELMET VANGA",
    "HEPATIC TANAGER", "HIMALAYAN BLUETAIL", "HIMALAYAN MONAL", "HOATZIN", "HOODED MERGANSER", "HOOPOES",
    "HORNED GUAN", "HORNED LARK", "HORNED SUNGEM", "HOUSE FINCH", "HOUSE SPARROW", "HYACINTH MACAW",
    "IBERIAN MAGPIE", "IBISBILL", "IMPERIAL SHAQ", "INCA TERN", "INDIAN BUSTARD", "INDIAN PITTA",
    "INDIAN ROLLER", "INDIAN VULTURE", "INDIGO BUNTING", "INDIGO FLYCATCHER", "INLAND DOTTEREL",
    "IVORY BILLED ARACARI", "IVORY GULL", "IWI", "JABIRU", "JACK SNIPE", "JACOBIN PIGEON", "JANDAYA PARAKEET",
    "JAPANESE ROBIN", "JAVA SPARROW", "JOCOTOCO ANTPITTA", "KAGU", "KAKAPO", "KILLDEAR", "KING EIDER",
    "KING VULTURE", "KIWI", "KOOKABURRA", "LARK BUNTING", "LAUGHING GULL", "LAZULI BUNTING", "LESSER ADJUTANT",
    "LILAC ROLLER", "LIMPKIN", "LITTLE AUK", "LOGGERHEAD SHRIKE", "LONG-EARED OWL", "LOONEY BIRDS",
    "LUCIFER HUMMINGBIRD", "MAGPIE GOOSE", "MALABAR HORNBILL", "MALACHITE KINGFISHER", "MALAGASY WHITE EYE",
    "MALEO", "MALLARD DUCK", "MANDRIN DUCK", "MANGROVE CUCKOO", "MARABOU STORK", "MASKED BOBWHITE",
    "MASKED BOOBY", "MASKED LAPWING", "MCKS BUNTING", "LAUGHING GULL", "LAZULI BUNTING", "LESSER ADJUTANT",
    "LILAC ROLLER", "LIMPKIN", "LITTLE AUK", "LOGGERHEAD SHRIKE", "LONG-EARED OWL", "LOONEY BIRDS",
    "LUCIFER HUMMINGBIRD", "MAGPIE GOOSE", "MALABAR HORNBILL", "MALACHITE KINGFISHER", "MALAGASY WHITE EYE",
    "MALEO", "MALLARD DUCK", "MANDRIN DUCK", "MANGROVE CUCKOO", "MARABOU STORK", "MASKED BOBWHITE",
    "MASKED BOOBY", "MASKED LAPWING", "MCKAYS BUNTING", "MERLIN", "MIKADO  PHEASANT", "MILITARY MACAW",
    "MOURNING DOVE", "MYNA", "NICOBAR PIGEON", "NOISY FRIARBIRD", "NORTHERN BEARDLESS TYRANNULET", "NORTHERN CARDINAL",
    "NORTHERN FLICKER", "NORTHERN FULMAR", "NORTHERN GANNET", "NORTHERN GOSHAWK", "NORTHERN JACANA",     "NORTHERN MOCKINGBIRD", "NORTHERN PARULA", "NORTHERN RED BISHOP", "NORTHERN SHOVELER", "OCELLATED TURKEY",
    "OKINAWA RAIL", "ORANGE BREASTED TROGON", "ORANGE BRESTED BUNTING", "ORIENTAL BAY OWL", "ORNATE HAWK EAGLE",
    "OSPREY", "OSTRICH", "OVENBIRD", "OYSTER CATCHER", "PAINTED BUNTING", "PALILA", "PALM NUT VULTURE",
    "PARADISE TANAGER", "PARAKETT  AKULET", "PARUS MAJOR", "PATAGONIAN SIERRA FINCH", "PEACOCK",
    "PEREGRINE FALCON", "PHAINOPEPLA", "PHILIPPINE EAGLE", "PINK ROBIN", "PLUSH CRESTED JAY", "POMARINE JAEGER",
    "PUFFIN", "PUNA TEAL", "PURPLE FINCH", "PURPLE GALLINULE", "PURPLE MARTIN", "PURPLE SWAMPHEN",
    "PYGMY KINGFISHER", "PYRRHULOXIA", "QUETZAL", "RAINBOW LORIKEET", "RAZORBILL", "RED BEARDED BEE EATER",
    "RED BELLIED PITTA", "RED BILLED TROPICBIRD", "RED BROWED FINCH", "RED FACED CORMORANT", "RED FACED WARBLER",
    "RED FODY", "RED HEADED DUCK", "RED HEADED WOODPECKER", "RED KNOT", "RED LEGGED HONEYCREEPER", "RED NAPED TROGON",
    "RED SHOULDERED HAWK", "RED TAILED HAWK", "RED TAILED THRUSH", "RED WINGED BLACKBIRD", "RED WISKERED BULBUL",
    "REGENT BOWERBIRD", "RING-NECKED PHEASANT", "ROADRUNNER", "ROCK DOVE", "ROSE BREASTED COCKATOO", "ROSE BREASTED GROSBEAK",
    "ROSEATE SPOONBILL", "ROSY FACED LOVEBIRD", "ROUGH LEG BUZZARD", "ROYAL FLYCATCHER", "RUBY CROWNED KINGLET",
    "RUBY THROATED HUMMINGBIRD", "RUDDY SHELDUCK", "RUDY KINGFISHER", "RUFOUS KINGFISHER", "RUFOUS TREPE",
    "RUFUOS MOTMOT", "SAMATRAN THRUSH", "SAND MARTIN", "SANDHILL CRANE", "SATYR TRAGOPAN", "SAYS PHOEBE",
    "SCARLET CROWNED FRUIT DOVE", "SCARLET FACED LIOCICHLA", "SCARLET IBIS", "SCARLET MACAW", "SCARLET TANAGER",
    "SHOEBILL", "SHORT BILLED DOWITCHER", "SMITHS LONGSPUR", "SNOW GOOSE", "SNOW PARTRIDGE", "SNOWY EGRET",
    "SNOWY OWL", "SNOWY PLOVER", "SORA", "SPANGLED COTINGA", "SPLENDID WREN", "SPOON BILED SANDPIPER",
    "SPOTTED CATBIRD", "SPOTTED WHISTLING DUCK", "SQUACCO HERON", "SRI LANKA BLUE MAGPIE", "STEAMER DUCK",
    "STORK BILLED KINGFISHER", "STRIATED CARACARA", "STRIPED OWL", "STRIPPED MANAKIN", "STRIPPED SWALLOW",
    "SUNBITTERN", "SUPERB STARLING", "SURF SCOTER", "SWINHOES PHEASANT", "TAILORBIRD", "TAIWAN MAGPIE",
    "TAKAHE", "TASMANIAN HEN", "TAWNY FROGMOUTH", "TEAL DUCK", "TIT MOUSE", "TOUCHAN", "TOWNSENDS WARBLER",
    "TREE SWALLOW", "TRICOLORED BLACKBIRD", "TROPICAL KINGBIRD", "TRUMPTER SWAN", "TURKEY VULTURE",
    "TURQUOISE MOTMOT", "UMBRELLA BIRD", "VARIED THRUSH", "VEERY", "VENEZUELIAN TROUPIAL", "VERDIN",
    "VERMILION FLYCATHER", "VICTORIA CROWNED PIGEON", "VIOLET BACKED STARLING", "VIOLET CUCKOO",
    "VIOLET GREEN SWALLOW", "VIOLET TURACO", "VISAYAN HORNBILL", "VULTURINE GUINEAFOWL", "WALL CREAPER",
    "WATTLED CURASSOW", "WATTLED LAPWING", "WHIMBREL", "WHITE BREASTED WATERHEN", "WHITE BROWED CRAKE",
    "WHITE CHEEKED TURACO", "WHITE CRESTED HORNBILL", "WHITE EARED HUMMINGBIRD", "WHITE NECKED RAVEN",
    "WHITE TAILED TROPIC", "WHITE THROATED BEE EATER", "WHITE THROATED KINGFISHER", "WHITE WAGTAIL",
    "WHITE WINGED DOVE", "WHITE WOODPECKER", "WHITE-BELLIED SEA EAGLE", "WHITE-BREASTED KINGFISHER",
    "WHITE-CHEEKED BARBET", "WHITE-EARED SAPSUCKER", "WHITE-FACED IBIS", "WHITE-HEADED WREN", "WHITE-NECKED JACOBIN",
    "WHITE-RUMPED SHAMA", "WHITE-THROATED SPARROW", "WHITE-WINGED TERN", "WHITE-WISKERED PUFFBIRD", "WILD TURKEY",
    "WILSONS BIRD OF PARADISE", "WILSONS STORM PETREL", "WINTER WREN", "WIRE TAILED MANAKIN", "WOOD DUCK",
    "YELLOW BELLIED FLOWERPECKER", "YELLOW BELLIED PRINIA", "YELLOW CACIQUE", "YELLOW CROWNED NIGHT HERON",
    "YELLOW FACED GRASSQUIT", "YELLOW HEADED BLACKBIRD", "YELLOW RUMPED CACIQUE", "YELLOW WARBLER",
    "YELLOW WINGED TANAGER", "YELLOW-CASQUED HORNBILL", "YELLOW-HEADED PICATHARTES", "YELLOW-THROATED WARBLER",
    "YOUNGS DOUBLE COLLARED SUNBIRD", "YUCATAN JAY", "YUCATAN WREN", "ZEBRA DOVE", "ZENAIDA DOVE",
    "ZITTING CISTICOLA"
]

# Function to preprocess the image
def preprocess_image(image):
    # Resize the image to 224x224 pixels
    image = image.resize((224, 224))
    # Convert the image to a numpy array
    img_array = np.array(image)
    # Normalize the image
    img_array = img_array / 255.0
    # Reshape the image to (1, 224, 224, 3) to match the input shape of the model
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

# Function to make predictions
def predict(image):
    # Preprocess the input image
    processed_image = preprocess_image(image)
    # Make prediction
    predictions = model.predict(processed_image)
    # Get the predicted bird class
    predicted_class_index = np.argmax(predictions)
    predicted_class = bird_classes[predicted_class_index]
    return predicted_class, predictions[0][predicted_class_index]

# Streamlit app
def main():
    # Set title of the app
    st.title("Bird Species Classifier")
    # Allow the user to upload an image
    uploaded_image = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])
    if uploaded_image is not None:
        # Display the uploaded image
        image = Image.open(uploaded_image)
        st.image(image, caption='Uploaded Image.', use_column_width=True)
        # Make prediction when the 'Predict' button is clicked
        if st.button('Predict'):
            # Make prediction
            class_name, confidence = predict(image)
            # Display the predicted bird species and confidence score
            st.write(f"Prediction: {class_name}, Confidence: {confidence*100:.2f}%")

# Run the app
if __name__ == '__main__':
    main()